import{initializeApp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import{getAuth,signInAnonymously,onAuthStateChanged}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import{getFirestore,collection,addDoc,deleteDoc,doc,query,orderBy,limit,onSnapshot,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBjrFhYiYshFqg0TOiswCZSOHeKOrcKV08",authDomain:"vila-chat.firebaseapp.com",projectId:"vila-chat",storageBucket:"vila-chat.firebasestorage.app",messagingSenderId:"149766884961",appId:"1:149766884961:web:61d24e568eac9853c7e420",measurementId:"G-Z39EJ58NDP"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const messages=document.getElementById("messages"),form=document.getElementById("messageForm"),input=document.getElementById("messageInput"),counter=document.getElementById("counter"),nameDialog=document.getElementById("nameDialog"),nameForm=document.getElementById("nameForm"),nameInput=document.getElementById("nameInput"),currentName=document.getElementById("currentName"),onlineCount=document.getElementById("onlineCount"),emojiPanel=document.getElementById("emojiPanel");
let user=null,name=localStorage.getItem("vilaChatName")||"",avatar=localStorage.getItem("vilaChatAvatar")||"🙂",firstSnapshot=true,lastCount=0;
const prefs={dark:localStorage.getItem("vila_dark")==="1",sound:localStorage.getItem("vila_sound")==="1",theme:localStorage.getItem("vila_theme")||"green",emojiCategory:localStorage.getItem("vila_emojiCategory")||"todos",clearedAt:Number(localStorage.getItem("vila_clearedAt")||0)};
const emojiGroups={rostos:["😀","😃","😄","😁","😆","😅","😂","🤣","😊","😇","🙂","🙃","😉","😌","😍","🥰","😘","😎","🤓","🤩","🥳","😭","😢","😡","🤬","😱","🤔","🤨"],gestos:["👍","👎","👏","🙌","🙏","💪","🤝","👋","✌️","🤞","👌","👀","🫶","☝️","👉","👈"],coracoes:["❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔","💕","💖","💗","💓","💞","💘"],comida:["🍕","🍔","🍟","🌭","🌮","🍿","🍩","🍪","🍫","🍎","🍉","🍓","🍌","🍇","🍒","🥤"],diversao:["🔥","🎉","🎊","😂","💀","👻","🤖","😈","🎮","🏆","⚽","🎵","🚀","⭐","💯","✨"],objetos:["📱","💻","⌨️","🖱️","📷","🎧","🎤","📌","🔔","💡","🎁","💎","🛠️","⚡","☀️","🌙"]};
const allEmojis=[...new Set(Object.values(emojiGroups).flat())];
function applyPrefs(){document.body.classList.toggle("dark-mode",prefs.dark);document.body.classList.remove("theme-blue","theme-purple");if(prefs.theme!=="green")document.body.classList.add("theme-"+prefs.theme)}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove("show"),1600)}
function setAvatar(a){avatar=a;localStorage.setItem("vilaChatAvatar",a);document.getElementById("currentAvatar").textContent=a;document.getElementById("brandAvatar").textContent=a}
function openName(){nameInput.value=name;nameDialog.showModal()}
function updateCounter(){const n=input.value.length;counter.textContent=`${n}/1000`;counter.className=n>=950?"counter-danger":n>=850?"counter-warn":"counter-normal"}
function dayLabel(d){const x=new Date(d.getFullYear(),d.getMonth(),d.getDate()),now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),diff=Math.round((today-x)/86400000);if(diff===0)return"Hoje";if(diff===1)return"Ontem";return d.toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit",year:"numeric"})}
function buildEmojiPanel(){emojiPanel.innerHTML="";const cats=prefs.emojiCategory==="todos"?Object.keys(emojiGroups):[prefs.emojiCategory];for(const cat of cats){const title=document.createElement("div");title.className="emoji-category-title";title.textContent=cat[0].toUpperCase()+cat.slice(1);emojiPanel.append(title);for(const e of emojiGroups[cat]||[]){const b=document.createElement("button");b.type="button";b.textContent=e;b.title=e;b.onclick=()=>{input.value=(input.value+e).slice(0,1000);updateCounter();emojiPanel.hidden=true;input.focus()};emojiPanel.append(b)}}}
function openSettings(){const d=document.getElementById("settingsDialog");document.getElementById("settingsName").value=name;document.getElementById("darkModeToggle").checked=prefs.dark;document.getElementById("soundToggle").checked=prefs.sound;document.getElementById("themeSelect").value=prefs.theme;document.getElementById("emojiCategory").value=prefs.emojiCategory;renderAvatars();d.showModal()}
function renderAvatars(){const grid=document.getElementById("avatarGrid");grid.innerHTML="";["🙂","😀","😎","🤓","🥳","😈","👻","🤖","🐱","🐶","🦊","🐼","🐸","🦁","🐵","🐯","⚽","🎮","🚀","⭐","🔥","💀","💚","👑"].forEach(a=>{const b=document.createElement("button");b.type="button";b.textContent=a;if(a===avatar)b.classList.add("selected");b.onclick=()=>{setAvatar(a);renderAvatars()};grid.append(b)})}
function listen(){const q=query(collection(db,"messages"),orderBy("createdAt","asc"),limit(100));onSnapshot(q,snap=>{messages.innerHTML="";let lastDay="";snap.forEach(s=>{const m=s.data();const ts=m.createdAt?.toDate?m.createdAt.toDate():null;if(prefs.clearedAt&&ts&&ts.getTime()<=prefs.clearedAt)return;const label=ts?dayLabel(ts):"";if(label&&label!==lastDay){const sep=document.createElement("div");sep.className="date-separator";sep.textContent=label;messages.append(sep);lastDay=label}const box=document.createElement("article");box.className="message"+(m.uid===user.uid?" mine":"");box.dataset.id=s.id;const meta=document.createElement("div");meta.className="meta";meta.textContent=(m.avatar||"🙂")+" "+(m.name||"Anônimo");const time=document.createElement("span");time.className="time";time.textContent=ts?ts.toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"}):"";meta.append(time);const text=document.createElement("div");text.className="text";text.textContent=m.text||"";box.append(meta,text);const actions=document.createElement("div");actions.className="message-actions";const copy=document.createElement("button");copy.className="message-action";copy.textContent="📋";copy.title="Copiar";copy.onclick=()=>navigator.clipboard?.writeText(m.text||"").then(()=>toast("Mensagem copiada 📋"));actions.append(copy);if(m.uid===user.uid){const del=document.createElement("button");del.className="message-action";del.textContent="🗑️";del.title="Apagar";del.onclick=async()=>{if(confirm("Apagar esta mensagem?"))await deleteDoc(doc(db,"messages",s.id))};actions.append(del)}box.append(actions);messages.append(box)});messages.scrollTop=messages.scrollHeight;if(!firstSnapshot&&prefs.sound&&snap.size>lastCount)playSound();lastCount=snap.size;firstSnapshot=false},e=>console.error(e))}
function playSound(){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ac=new C(),o=ac.createOscillator(),g=ac.createGain();o.frequency.value=660;g.gain.value=.035;o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+.07)}catch(_){}}
applyPrefs();setAvatar(avatar);updateCounter();buildEmojiPanel();if(!name)openName();
document.getElementById("changeNameBtn").onclick=openName;document.getElementById("settingsBtn").onclick=openSettings;
nameForm.addEventListener("submit",e=>{if(e.submitter?.value==="save"){const n=nameInput.value.trim();if(!n){e.preventDefault();return}name=n.slice(0,20);localStorage.setItem("vilaChatName",name);currentName.textContent=name}});
input.addEventListener("input",updateCounter);document.getElementById("emojiBtn").onclick=()=>{emojiPanel.hidden=!emojiPanel.hidden;if(!emojiPanel.hidden)buildEmojiPanel()};
input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()} });
document.getElementById("searchBox").addEventListener("input",e=>{const q=e.target.value.trim().toLowerCase();[...messages.querySelectorAll(".message")].forEach(x=>x.style.display=!q||x.innerText.toLowerCase().includes(q)?"":"none")});
document.getElementById("clearViewBtn").onclick=()=>{prefs.clearedAt=Date.now();localStorage.setItem("vila_clearedAt",String(prefs.clearedAt));[...messages.querySelectorAll(".message,.date-separator")].forEach(x=>x.remove());toast("Tela limpa só neste dispositivo 🧹")};
document.getElementById("settingsSaveName").onclick=()=>{const n=document.getElementById("settingsName").value.trim();if(!n)return;name=n.slice(0,20);localStorage.setItem("vilaChatName",name);currentName.textContent=name;toast("Nome salvo ✅")};
document.getElementById("darkModeToggle").onchange=e=>{prefs.dark=e.target.checked;localStorage.setItem("vila_dark",prefs.dark?"1":"0");applyPrefs()};document.getElementById("soundToggle").onchange=e=>{prefs.sound=e.target.checked;localStorage.setItem("vila_sound",prefs.sound?"1":"0")};document.getElementById("themeSelect").onchange=e=>{prefs.theme=e.target.value;localStorage.setItem("vila_theme",prefs.theme);applyPrefs()};document.getElementById("emojiCategory").onchange=e=>{prefs.emojiCategory=e.target.value;localStorage.setItem("vila_emojiCategory",prefs.emojiCategory);buildEmojiPanel()};
form.onsubmit=async e=>{e.preventDefault();if(!user)return;const text=input.value.trim();if(!text)return;try{await addDoc(collection(db,"messages"),{name:name||"Anônimo",avatar,text:text.slice(0,1000),uid:user.uid,createdAt:serverTimestamp()})input.value="";updateCounter();input.focus()}catch(e){console.error(e);alert("Erro ao enviar a mensagem")}};
signInAnonymously(auth).catch(e=>{console.error(e);onlineCount.textContent="Erro ao conectar"});onAuthStateChanged(auth,u=>{user=u;if(u){onlineCount.textContent="Online";listen()}});
